// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Coral.Employee.Persistance.Entities
{
    public partial class EmployeeBasicInfo
    {
        public string EmployeeId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string ContactNumber { get; set; }
        public string OfficeEmail { get; set; }
        public string Address { get; set; }
        public string FatherName { get; set; }
        public string SpouseName { get; set; }
        public int StatusId { get; set; }
        public int MaritalStatusId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}